numberOfSeries: 1
numberOfFramesInOneSeries: 5
SizeX: 500
SizeY: 500
dataFile: C:\Users\Admin\OneDrive\SKOLA\DIPLOMOVKA\masterThesis\stargen\data # /media/daniel/Windows/Users/user/Dropbox/diplomovka/stargen/data  #
plot: True
saveImages: True

Stars:
  count:
    min: 10
    max: 30
    random: uniform

  brightness:
    min: 1000
    max: 10000
    random: uniform

  fwhm:
    min: 2
    max: 2
    random: uniform

  # method: line/gauss
  method: gauss

  # streak properties
  # applied only when method is line
  length:
    min: 5
    max: 25
    random: uniform*

  alpha:
    min: 0
    max: 360
    random: uniform*

Objects:
  enable: False

  count:
    min: 1
    max: 1
    random: uniform

  brightness:
    min: 1000
    max: 10000
    random: uniform

  fwhm:
    min: 3
    max: 3
    random: uniform

  # speed of object traveled % of the screen in one series
  # if frame is not a square, smallest dimension will be considered
  speed:
    min: 30
    max: 90
    random: uniform

  # determines the direction of the motion
  alpha:
    min: 0
    max: 360
    random: uniform

  # method: line/gauss
  method: gauss

  # streak properties
  # applied only when method is line
  length:
    min: 5
    max: 25
    random: uniform

Clusters:
  enable: False

  count:
    min: 1
    max: 1
    random: uniform

  objectCountPerCluster:
    min: 3
    max: 3
    random: uniform

  brightness:
    min: 1000
    max: 10000
    random: uniform

  fwhm:
    min: 3
    max: 10
    random: uniform

  # speed of objects traveled % of the screen in one series
  # if frame is not a square, smallest dimension will be considered
  speed:
    min: 30
    max: 80
    random: uniform

  # determines the direction of the motion
  alpha:
    min: 0
    max: 360
    random: uniform

  # method: line/gauss
  method: gauss

  # streak properties
  # applied only when method is line
  length:
    min: 10
    max: 50
    random: uniform

Noise:
    mean: 10
    std: 7
    enable: False

Bias:
    value: 20
    columns: 25
    enable: False

HotPixel:
    count: 15

    brightness:
      min: 5000
      max: 10000
      random: uniform

    enable: True

CosmicRays:
  count:
    min: 10
    max: 50
    random: uniform

  brightness:
    min: 10000
    max: 65000
    random: uniform

  # pixel count for worms and tracks
  pixelCount:
    min: 10
    max: 50
    random: uniform

  # pixel count for spots
  spotPixelCount:
    min: 1
    max: 10
    random: uniform

  enable: False