# indicates whether to read configuration of stars and object from file
# number of stars, their positions and brightness wil be determined from the file
# stars will be drawn as streaks and their fwhm, length, alpha will be computed from the config
# object will be drawn as a point and his fwhm will be computed from the config
realData:
  enabled: False
  file: C:\Users\Admin\OneDrive\SKOLA\DIPLOMOVKA\masterThesis\stargen\realData\00040A_2_R_15-09-21_00..02..24

# number of generated series
numberOfSeries: 10

# number of frames in one series
# if realData is enabled number of frames depends on the object file and this value is not used
numberOfFramesInOneSeries: 5

# dimensions of the image
SizeX: 50
SizeY: 50

# destination where to save files
dataFile: C:\Users\Admin\OneDrive\SKOLA\DIPLOMOVKA\masterThesis\stargen\data # /media/daniel/Windows/Users/user/Dropbox/diplomovka/stargen/data  #

# indicates whether to plot images
plot: False

# indicates whether to save FITS images
saveImages: True


Stars:
  # indicates whether to use real data from the file
  # number of stars, their positions and brightness will be determined from the file
  # fwhm, length, alpha and drawing method will be computed using values in configuration
  realData:
    enabled: False
    file: C:\Users\Admin\OneDrive\SKOLA\DIPLOMOVKA\masterThesis\stargen\realData\00040A_2_R_15-09-21_00..02..24\00040A_2_R-0001_m_s.tsv

  count:
    min: 0
    max: 0
    random: uniform

  brightness:
    min: 10000
    max: 50000
    random: uniform

  fwhm:
    min: 2
    max: 2
    random: uniform

  # method: line/gauss
  method: gauss

  # streak properties
  # applied only when method is line
  length:
    min: 5
    max: 25
    random: uniform*

  alpha:
    min: 0
    max: 360
    random: uniform*

Objects:
  enable: True

  count:
    min: 1
    max: 1
    random: uniform

  brightness:
    min: 10000
    max: 50000
    random: uniform

  fwhm:
    min: 2
    max: 2
    random: uniform

  # speed of object traveled % of the screen in one series
  # if frame is not a square, smallest dimension will be considered
  speed:
    min: 10
    max: 20
    random: uniform

  # determines the direction of the motion
  alpha:
    min: 0
    max: 360
    random: uniform

  # method: line/gauss
  method: line

  # streak properties
  # applied only when method is line
  length:
    min: 15
    max: 50
    random: uniform

Clusters:
  enable: False

  count:
    min: 1
    max: 1
    random: uniform

  objectCountPerCluster:
    min: 3
    max: 3
    random: uniform

  brightness:
    min: 1000
    max: 10000
    random: uniform

  fwhm:
    min: 3
    max: 10
    random: uniform

  # speed of objects traveled % of the screen in one series
  # if frame is not a square, smallest dimension will be considered
  speed:
    min: 30
    max: 80
    random: uniform

  # determines the direction of the motion
  alpha:
    min: 0
    max: 360
    random: uniform

  # method: line/gauss
  method: gauss

  # streak properties
  # applied only when method is line
  length:
    min: 10
    max: 50
    random: uniform

Galaxies:
  enable: False

  count:
    min: 1
    max: 5
    random: uniform

  # surface brightness at radius
  brightness:
    min: 50
    max: 50
    random: uniform

  # rotation angle
  alpha:
    min: 0
    max: 360
    random: uniform

  ellipticity:
    min: 0.1
    max: 0.4
    random: uniform

  sersicIndex:
    min: 1
    max: 1.5
    random: uniform

  # effective (half-light) radius
  radius:
    min: 5
    max: 10
    random: uniform


Noise:
  enable: True
  mean: 100
  std: 50

Bias:
  enable: False
  value: 20
  columns: 25

HotPixel:
  enable: True

  count: 50

  brightness:
    min: 5000
    max: 10000
    random: uniform

  # if randomSeed is number, then this number will be used as 'random seed' to generate hot pixels
  # if its random then 'random seed' will be generated randomly for each series (this is for purposes of training NN)
  randomSeed: random

CosmicRays:
  enable: True

  count:
    min: 2
    max: 10
    random: uniform

  brightness:
    min: 10000
    max: 50000
    random: uniform

  # pixel count for worms and tracks
  pixelCount:
    min: 10
    max: 40
    random: uniform

  # pixel count for spots
  spotPixelCount:
    min: 2
    max: 10
    random: uniform
