# indicates whether to read configuration of stars and object from file
# number of stars, their positions and brightness wil be determined from the file
# stars will be drawn as streaks and their fwhm, length, alpha will be computed from the config
# object will be drawn as a point and his fwhm will be computed from the config
realData:
  enabled: True
  file: C:\Users\Admin\OneDrive\SKOLA\DIPLOMOVKA\masterThesis\stargen\realData\00040A_2_R_15-09-21_00..02..24

# number of generated series
numberOfSeries: 1

# number of frames in one series
# if realData is enabled number of frames depends on the object file and this value is not used
numberOfFramesInOneSeries: 5

# dimensions of the image
SizeX: 1024
SizeY: 1024

# destination where to save files
dataFile: C:\Users\Admin\OneDrive\SKOLA\DIPLOMOVKA\masterThesis\stargen\data # /media/daniel/Windows/Users/user/Dropbox/diplomovka/stargen/data  #

# indicates whether to plot images
plot: False

# indicates whether to save FITS images
saveImages: True

Stars:
  # indicates whether to use real data from the file
  # number of stars, their positions and brightness will be determined from the file
  # fwhm, length, alpha and drawing method will be computed using values in configuration
  realData:
    enabled: True
    file: C:\Users\Admin\OneDrive\SKOLA\DIPLOMOVKA\masterThesis\stargen\realData\00040A_2_R_15-09-21_00..02..24\00040A_2_R-0001_m_s.tsv

  count:
    min: 10
    max: 30
    random: uniform

  brightness:
    min: 1000
    max: 10000
    random: uniform

  fwhm:
    min: 2
    max: 2
    random: uniform

  # method: line/gauss
  method: line

  # streak properties
  # applied only when method is line
  length:
    min: 5
    max: 25
    random: uniform*

  alpha:
    min: 0
    max: 360
    random: uniform*

Objects:
  enable: True

  count:
    min: 1
    max: 1
    random: uniform

  brightness:
    min: 1000
    max: 10000
    random: uniform

  fwhm:
    min: 3
    max: 3
    random: uniform

  # speed of object traveled % of the screen in one series
  # if frame is not a square, smallest dimension will be considered
  speed:
    min: 30
    max: 90
    random: uniform

  # determines the direction of the motion
  alpha:
    min: 0
    max: 360
    random: uniform

  # method: line/gauss
  method: gauss

  # streak properties
  # applied only when method is line
  length:
    min: 5
    max: 25
    random: uniform

Clusters:
  enable: False

  count:
    min: 1
    max: 1
    random: uniform

  objectCountPerCluster:
    min: 3
    max: 3
    random: uniform

  brightness:
    min: 1000
    max: 10000
    random: uniform

  fwhm:
    min: 3
    max: 10
    random: uniform

  # speed of objects traveled % of the screen in one series
  # if frame is not a square, smallest dimension will be considered
  speed:
    min: 30
    max: 80
    random: uniform

  # determines the direction of the motion
  alpha:
    min: 0
    max: 360
    random: uniform

  # method: line/gauss
  method: gauss

  # streak properties
  # applied only when method is line
  length:
    min: 10
    max: 50
    random: uniform

Noise:
    mean: 10
    std: 7
    enable: True

Bias:
    value: 20
    columns: 25
    enable: False

HotPixel:
    count: 15

    brightness:
      min: 5000
      max: 10000
      random: uniform

    enable: True

CosmicRays:
  count:
    min: 10
    max: 50
    random: uniform

  brightness:
    min: 1000
    max: 5000
    random: uniform

  # pixel count for worms and tracks
  pixelCount:
    min: 10
    max: 50
    random: uniform

  # pixel count for spots
  spotPixelCount:
    min: 1
    max: 10
    random: uniform

  enable: True